version: "3.5"

services:
  grafana:
    image: grafana/grafana:6.7.3
    ports:
    - "3000:3000"
    volumes:
    - ./dist:/var/lib/grafana/plugins/jdbranham-diagram-panel
    environment:
    - TERM=linux
